### ISSUE TITLE
buidling on macpro m1max fails.

### ISSUE THREAD

**Issue by pgee70** [pikepdf/pikepdf#283]
I am migrating from an intel mac to an m1max mac with the arm64 processor.

i am afaid i don't understand the compiler output at all but it is:

any ideas on how to get it working?

```
pgee@mbp2021 Caches % uname -a
Darwin mbp2021.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:41 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T6000 arm64

pgee@mbp2021 Caches % pip debug
WARNING: This command is only meant for debugging. Do not use this with automation for parsing and getting these details, since the output and options of this command may change without notice.
pip version: pip 21.3.1 from /Library/Python/3.8/site-packages/pip (python 3.8)
sys.version: 3.8.9 (default, Oct 26 2021, 07:25:53)
[Clang 13.0.0 (clang-1300.0.29.30)]
sys.executable: /Applications/Xcode.app/Contents/Developer/usr/bin/python3
sys.getdefaultencoding: utf-8
sys.getfilesystemencoding: utf-8
locale.getpreferredencoding: UTF-8
sys.platform: darwin
sys.implementation:
  name: cpython
'cert' config value: Not specified
REQUESTS_CA_BUNDLE: None
CURL_CA_BUNDLE: None
pip._vendor.certifi.where(): /Library/Python/3.8/site-packages/pip/_vendor/certifi/cacert.pem
pip._vendor.DEBUNDLED: False
vendored library versions:
  CacheControl==0.12.6
  colorama==0.4.4
  distlib==0.3.3
  distro==1.6.0
  html5lib==1.1
  msgpack==1.0.2 (Unable to locate actual module version, using vendor.txt specified version)
  packaging==21.0
  pep517==0.12.0
  platformdirs==2.4.0
  progress==1.6
  pyparsing==2.4.7
  requests==2.26.0
  certifi==2021.05.30
  chardet==4.0.0
  idna==3.2
  urllib3==1.26.7
  resolvelib==0.8.0
  setuptools==44.0.0 (Unable to locate actual module version, using vendor.txt specified version)
  six==1.16.0
  tenacity==8.0.1 (Unable to locate actual module version, using vendor.txt specified version)
  tomli==1.0.3
  webencodings==0.5.1 (Unable to locate actual module version, using vendor.txt specified version)
Compatible tags: 334
  cp38-cp38-macosx_12_0_arm64
  cp38-cp38-macosx_12_0_universal2
  cp38-cp38-macosx_11_0_arm64
  cp38-cp38-macosx_11_0_universal2
  cp38-cp38-macosx_10_16_universal2
  cp38-cp38-macosx_10_15_universal2
  cp38-cp38-macosx_10_14_universal2
  cp38-cp38-macosx_10_13_universal2
  cp38-cp38-macosx_10_12_universal2
  cp38-cp38-macosx_10_11_universal2
  ...
  [First 10 tags shown. Pass --verbose to show all.]


pgee@mbp2021 Caches % sudo pip3 install pikepdf
WARNING: The directory '/Users/pgee/Library/Caches/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.
Collecting pikepdf
  Downloading pikepdf-4.2.0.tar.gz (2.3 MB)
     |████████████████████████████████| 2.3 MB 2.4 MB/s
  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/tmp/pip-build-env-w9hayy15/normal/lib/python3.8/site-packages
  sysconfig: /Library/Python/3.8/site-packages
  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/tmp/pip-build-env-w9hayy15/normal/lib/python3.8/site-packages
  sysconfig: /Library/Python/3.8/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = '/private/tmp/pip-build-env-w9hayy15/normal'
  WARNING: Value for prefixed-purelib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages
  sysconfig: /Library/Python/3.8/site-packages
  WARNING: Value for prefixed-platlib does not match. Please report this to <https://github.com/pypa/pip/issues/10151>
  distutils: /private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages
  sysconfig: /Library/Python/3.8/site-packages
  WARNING: Additional context:
  user = False
  home = None
  root = None
  prefix = '/private/tmp/pip-build-env-w9hayy15/overlay'
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Pillow>=6.0
  Downloading Pillow-8.4.0-cp38-cp38-macosx_11_0_arm64.whl (2.8 MB)
     |████████████████████████████████| 2.8 MB 10.9 MB/s
Collecting lxml>=4.0
  Downloading lxml-4.7.1.tar.gz (3.2 MB)
     |████████████████████████████████| 3.2 MB 9.9 MB/s
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pikepdf, lxml
  Building wheel for pikepdf (pyproject.toml) ... error
  ERROR: Command errored out with exit status 1:
   command: /Applications/Xcode.app/Contents/Developer/usr/bin/python3 /Library/Python/3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /tmp/tmpek522aic
       cwd: /private/tmp/pip-install-n5v8qusr/pikepdf_00239daa4cbb4acaac7077d07efd27d2
  Complete output (107 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-arm64-3.8
  creating build/lib.macosx-10.14-arm64-3.8/pikepdf
  copying src/pikepdf/_methods.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf
  copying src/pikepdf/_version.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf
  copying src/pikepdf/__init__.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf
  copying src/pikepdf/_cpphelpers.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf
  copying src/pikepdf/jbig2.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf
  copying src/pikepdf/_xml.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf
  copying src/pikepdf/objects.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf
  copying src/pikepdf/codec.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf
  creating build/lib.macosx-10.14-arm64-3.8/pikepdf/models
  copying src/pikepdf/models/matrix.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf/models
  copying src/pikepdf/models/encryption.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf/models
  copying src/pikepdf/models/metadata.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf/models
  copying src/pikepdf/models/__init__.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf/models
  copying src/pikepdf/models/outlines.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf/models
  copying src/pikepdf/models/image.py -> build/lib.macosx-10.14-arm64-3.8/pikepdf/models
  running egg_info
  writing src/pikepdf.egg-info/PKG-INFO
  writing dependency_links to src/pikepdf.egg-info/dependency_links.txt
  writing requirements to src/pikepdf.egg-info/requires.txt
  writing top-level names to src/pikepdf.egg-info/top_level.txt
  listing git files failed - pretending there aren't any
  reading manifest file 'src/pikepdf.egg-info/SOURCES.txt'
  writing manifest file 'src/pikepdf.egg-info/SOURCES.txt'
  copying src/pikepdf/_qpdf.pyi -> build/lib.macosx-10.14-arm64-3.8/pikepdf
  copying src/pikepdf/py.typed -> build/lib.macosx-10.14-arm64-3.8/pikepdf
  running build_ext
  building 'pikepdf._qpdf' extension
  creating build/temp.macosx-10.14-arm64-3.8
  creating build/temp.macosx-10.14-arm64-3.8/src
  creating build/temp.macosx-10.14-arm64-3.8/src/qpdf
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/embeddedfiles.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/embeddedfiles.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/annotation.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/annotation.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/nametree.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/nametree.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/object.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/object.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/object_repr.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/object_repr.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/page.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/page.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/pikepdf.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/pikepdf.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/pipeline.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/pipeline.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/parsers.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/parsers.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/object_convert.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/object_convert.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  src/qpdf/embeddedfiles.cpp:9:10: fatal error: 'qpdf/Constants.h' file not found
  #include <qpdf/Constants.h>
           ^~~~~~~~~~~~~~~~~~
  src/qpdf/annotation.cpp:9:10: fatal error: 'qpdf/Constants.h' file not found
  #include <qpdf/Constants.h>
           ^~~~~~~~~~~~~~~~~~
  src/qpdf/nametree.cpp:9:10: fatal error: 'qpdf/Constants.h' file not found
  #include <qpdf/Constants.h>
           ^~~~~~~~~~~~~~~~~~
  src/qpdf/pipeline.cpp:9:10: fatal error: 'qpdf/Constants.h' file not found
  #include <qpdf/Constants.h>
           ^~~~~~~~~~~~~~~~~~
  src/qpdf/object.cpp:12:10: fatal error: 'qpdf/Constants.h' file not found
  #include <qpdf/Constants.h>
           ^~~~~~~~~~~~~~~~~~
  src/qpdf/object_convert.cpp:17:10: fatal error: 'qpdf/Constants.h' file not found
  #include <qpdf/Constants.h>
           ^~~~~~~~~~~~~~~~~~
  src/qpdf/object_repr.cpp:24:10: fatal error: 'qpdf/Constants.h' file not found
  #include <qpdf/Constants.h>
           ^~~~~~~~~~~~~~~~~~
  In file included from src/qpdf/parsers.cpp:12:
  src/qpdf/pikepdf.h:15:10: fatal error: 'qpdf/PointerHolder.hh' file not found
  #include <qpdf/PointerHolder.hh>
           ^~~~~~~~~~~~~~~~~~~~~~~
  In file included from src/qpdf/page.cpp:14:
  src/qpdf/pikepdf.h:15:10: fatal error: 'qpdf/PointerHolder.hh' file not found
  #include <qpdf/PointerHolder.hh>
           ^~~~~~~~~~~~~~~~~~~~~~~
  In file included from src/qpdf/pikepdf.cpp:18:
  src/qpdf/pikepdf.h:15:10: fatal error: 'qpdf/PointerHolder.hh' file not found
  #include <qpdf/PointerHolder.hh>
           ^~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  1 error generated.
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/qpdf.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/qpdf.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  1 error generated.
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/qpdf_pagelist.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/qpdf_pagelist.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -I/private/tmp/pip-build-env-w9hayy15/overlay/lib/python3.8/site-packages/pybind11/include -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -c src/qpdf/rectangle.cpp -o build/temp.macosx-10.14-arm64-3.8/src/qpdf/rectangle.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
  1 error generated.
  error: command 'clang' failed with exit status 1
  1 error generated.
  1 error generated.
  src/qpdf/rectangle.cpp:9:10: fatal error: 'qpdf/QPDFObjectHandle.hh' file not found
  #include <qpdf/QPDFObjectHandle.hh>
           ^~~~~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  1 error generated.
  1 error generated.
  1 error generated.
  In file included from src/qpdf/qpdf_pagelist.cpp:9:
  src/qpdf/pikepdf.h:15:10: fatal error: 'qpdf/PointerHolder.hh' file not found
  #include <qpdf/PointerHolder.hh>
           ^~~~~~~~~~~~~~~~~~~~~~~
  In file included from src/qpdf/qpdf.cpp:14:
  src/qpdf/pikepdf.h:15:10: fatal error: 'qpdf/PointerHolder.hh' file not found
  #include <qpdf/PointerHolder.hh>
           ^~~~~~~~~~~~~~~~~~~~~~~
  1 error generated.
  1 error generated.
  1 error generated.
  ----------------------------------------
  ERROR: Failed building wheel for pikepdf
  Building wheel for lxml (setup.py) ... \
done
  Created wheel for lxml: filename=lxml-4.7.1-cp38-cp38-macosx_10_14_arm64.whl size=3003202 sha256=945b541da746af0c79e3f088c9a46ca675a02bd582ac06431e84c347b1fbc887
  Stored in directory: /private/tmp/pip-ephem-wheel-cache-l11trgoc/wheels/c7/d8/ac/9c62a8804498b75b652f0cfbe020c93ae3f7265a9bbb40cee9
Successfully built lxml
Failed to build pikepdf
ERROR: Could not build wheels for pikepdf, which is required to install pyproject.toml-based projects
pgee@mbp2021 Caches %



```

**Comment by jbarlow83** [comment]
If you use Python 3.9 or 3.10 the binary wheel will be installed without compiling. Easiest answer is to use a newer Python. (Python 3.8 on Apple Silicon isn't that well supported by anyone.)

If you need to compile, the documentation has instructions that may help. 

Also it is usually preferable to avoid sudo pip install - just install as a user.

**Comment by pgee70** [comment]
@jbarlow83  thanks! my version of pip was set to 3.8 for some reason - so used ports to install a new version of pip for python3.9, selected python3.9 as default python 3 and finally got there!

**Comment by peterkelly** [comment]
I was able to get it to build with Python 3.8 on macOS M1, with the following steps:

```
cd /opt/homebrew/opt/qpdf
mkdir -p libqpdf/build
cd libqpdf/build
ln -s ../../lib .libs
```

Followed by:
```
QPDF_SOURCE_TREE=/opt/homebrew/opt/qpdf pip install pikepdf
```

There's some logic near the top of `setup.py` which sets the includes and library dirs for qpdf. If this were amended to take into account the above (and use `/opt/homebrew/opt/qpdf/include` and `/opt/homebrew/opt/qpdf/lib` if they exist) then this would make it possible to build from source.

I understand the problem is already solved for Python 3.9 and 3.10, but for various reasons some people are still using Python 3.8, and for those people solution should work.

**Comment by jbarlow83** [comment]
@peterkelly If you use homebrew it will configure Python to automatically look in its include/ and lib/ folders when building extension modules. Part of the job of a package manager is setting up this sort of thing. That is why managed Python + managed qpdf can build pikepdf. 

I'm not too keen on adding a shim for the special case of unmanaged Python and managed qpdf. If Python is unmanaged, you need to specify where your libraries are. It's best to leave it this way - for example your code won't work with Intel Mac (or arm64 running x64 emulation) because the paths are different. 

The documentation does discuss the use of QPDF_SOURCE_TREE but maybe should be expanded to discuss these issues. 

It's cleaner to "make install" qpdf and then adjust CXXFLAGS and LDFLAGS for a production install.

**Comment by peterkelly** [comment]
@jbarlow83 I've just tried with the homebrew installation of Python 3.8 and it works perfectly. I agree this is a cleaner approach.

Thanks

**Comment by sypianski** [comment]
I'm using pip 22.0.3 with python 3.9 and I'm still having this problem.

<details>
<summary>click</summary>

```
pip3.9 install pikepdf 
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Collecting pikepdf
  Using cached pikepdf-5.0.0.tar.gz (2.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting Pillow<10,>=6.0
  Using cached Pillow-9.0.1-1-cp39-cp39-macosx_11_0_arm64.whl (2.7 MB)
Collecting packaging>=20
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting lxml>=4.0
  Using cached lxml-4.7.1-cp39-cp39-macosx_12_0_arm64.whl
Collecting pyparsing!=3.0.5,>=2.0.2
  Using cached pyparsing-3.0.7-py3-none-any.whl (98 kB)
Building wheels for collected packages: pikepdf
  Building wheel for pikepdf (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for pikepdf (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [81 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12-arm64-3.9
      creating build/lib.macosx-12-arm64-3.9/pikepdf
      copying src/pikepdf/_methods.py -> build/lib.macosx-12-arm64-3.9/pikepdf
      copying src/pikepdf/_version.py -> build/lib.macosx-12-arm64-3.9/pikepdf
      copying src/pikepdf/__init__.py -> build/lib.macosx-12-arm64-3.9/pikepdf
      copying src/pikepdf/_cpphelpers.py -> build/lib.macosx-12-arm64-3.9/pikepdf
      copying src/pikepdf/jbig2.py -> build/lib.macosx-12-arm64-3.9/pikepdf
      copying src/pikepdf/_xml.py -> build/lib.macosx-12-arm64-3.9/pikepdf
      copying src/pikepdf/objects.py -> build/lib.macosx-12-arm64-3.9/pikepdf
      copying src/pikepdf/codec.py -> build/lib.macosx-12-arm64-3.9/pikepdf
      creating build/lib.macosx-12-arm64-3.9/pikepdf/models
      copying src/pikepdf/models/matrix.py -> build/lib.macosx-12-arm64-3.9/pikepdf/models
      copying src/pikepdf/models/_transcoding.py -> build/lib.macosx-12-arm64-3.9/pikepdf/models
      copying src/pikepdf/models/encryption.py -> build/lib.macosx-12-arm64-3.9/pikepdf/models
      copying src/pikepdf/models/metadata.py -> build/lib.macosx-12-arm64-3.9/pikepdf/models
      copying src/pikepdf/models/_content_stream.py -> build/lib.macosx-12-arm64-3.9/pikepdf/models
      copying src/pikepdf/models/__init__.py -> build/lib.macosx-12-arm64-3.9/pikepdf/models
      copying src/pikepdf/models/outlines.py -> build/lib.macosx-12-arm64-3.9/pikepdf/models
      copying src/pikepdf/models/image.py -> build/lib.macosx-12-arm64-3.9/pikepdf/models
      running egg_info
      listing git files failed - pretending there aren't any
      writing manifest file 'src/pikepdf.egg-info/SOURCES.txt'
      copying src/pikepdf/_qpdf.pyi -> build/lib.macosx-12-arm64-3.9/pikepdf
      copying src/pikepdf/py.typed -> build/lib.macosx-12-arm64-3.9/pikepdf
      running build_ext
      creating build/temp.macosx-12-arm64-3.9
      creating build/temp.macosx-12-arm64-3.9/src
      creating build/temp.macosx-12-arm64-3.9/src/qpdf
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/private/var/folders/lp/xc0xj9hx5vd88zclq8jyw6_m0000gn/T/pip-build-env-vjrdj1rf/overlay/lib/python3.9/site-packages/pybind11/include -I/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/qpdf/annotation.cpp -o build/temp.macosx-12-arm64-3.9/src/qpdf/annotation.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/private/var/folders/lp/xc0xj9hx5vd88zclq8jyw6_m0000gn/T/pip-build-env-vjrdj1rf/overlay/lib/python3.9/site-packages/pybind11/include -I/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/qpdf/embeddedfiles.cpp -o build/temp.macosx-12-arm64-3.9/src/qpdf/embeddedfiles.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/private/var/folders/lp/xc0xj9hx5vd88zclq8jyw6_m0000gn/T/pip-build-env-vjrdj1rf/overlay/lib/python3.9/site-packages/pybind11/include -I/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/qpdf/nametree.cpp -o build/temp.macosx-12-arm64-3.9/src/qpdf/nametree.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/private/var/folders/lp/xc0xj9hx5vd88zclq8jyw6_m0000gn/T/pip-build-env-vjrdj1rf/overlay/lib/python3.9/site-packages/pybind11/include -I/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/qpdf/object.cpp -o build/temp.macosx-12-arm64-3.9/src/qpdf/object.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/private/var/folders/lp/xc0xj9hx5vd88zclq8jyw6_m0000gn/T/pip-build-env-vjrdj1rf/overlay/lib/python3.9/site-packages/pybind11/include -I/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/qpdf/object_convert.cpp -o build/temp.macosx-12-arm64-3.9/src/qpdf/object_convert.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/private/var/folders/lp/xc0xj9hx5vd88zclq8jyw6_m0000gn/T/pip-build-env-vjrdj1rf/overlay/lib/python3.9/site-packages/pybind11/include -I/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/qpdf/page.cpp -o build/temp.macosx-12-arm64-3.9/src/qpdf/page.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/private/var/folders/lp/xc0xj9hx5vd88zclq8jyw6_m0000gn/T/pip-build-env-vjrdj1rf/overlay/lib/python3.9/site-packages/pybind11/include -I/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/qpdf/parsers.cpp -o build/temp.macosx-12-arm64-3.9/src/qpdf/parsers.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/private/var/folders/lp/xc0xj9hx5vd88zclq8jyw6_m0000gn/T/pip-build-env-vjrdj1rf/overlay/lib/python3.9/site-packages/pybind11/include -I/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/qpdf/object_repr.cpp -o build/temp.macosx-12-arm64-3.9/src/qpdf/object_repr.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
      src/qpdf/annotation.cpp:9:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      src/qpdf/embeddedfiles.cpp:9:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      src/qpdf/nametree.cpp:9:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      src/qpdf/object.cpp:12:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      src/qpdf/object_convert.cpp:17:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      src/qpdf/object_repr.cpp:24:10: fatal error: 'qpdf/Constants.h' file not found
      #include <qpdf/Constants.h>
               ^~~~~~~~~~~~~~~~~~
      In file included from src/qpdf/parsers.cpp:12:
      src/qpdf/pikepdf.h:15:10: fatal error: 'qpdf/PointerHolder.hh' file not found
      #include <qpdf/PointerHolder.hh>
               ^~~~~~~~~~~~~~~~~~~~~~~
      In file included from src/qpdf/page.cpp:14:
      src/qpdf/pikepdf.h:15:10: fatal error: 'qpdf/PointerHolder.hh' file not found
      #include <qpdf/PointerHolder.hh>
               ^~~~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/private/var/folders/lp/xc0xj9hx5vd88zclq8jyw6_m0000gn/T/pip-build-env-vjrdj1rf/overlay/lib/python3.9/site-packages/pybind11/include -I/opt/homebrew/Cellar/python@3.9/3.9.10/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/qpdf/pikepdf.cpp -o build/temp.macosx-12-arm64-3.9/src/qpdf/pikepdf.o -fvisibility=hidden -g0 -stdlib=libc++ -std=c++17 -mmacosx-version-min=10.14
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      1 error generated.
      1 error generated.
      1 error generated.
      1 error generated.
      1 error generated.
      1 error generated.
      In file included from src/qpdf/pikepdf.cpp:18:
      src/qpdf/pikepdf.h:15:10: fatal error: 'qpdf/PointerHolder.hh' file not found
      #include <qpdf/PointerHolder.hh>
               ^~~~~~~~~~~~~~~~~~~~~~~
      1 error generated.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pikepdf
Failed to build pikepdf
ERROR: Could not build wheels for pikepdf, which is required to install pyproject.toml-based projects
```
</details>

**Comment by sypianski** [comment]
It worked with the first option, thank you!
